# FILE: _config.yml
title: IT skills-github-pages
description: Tips, notes, and experiments
url: https://acmgllc.github.io
baseurl: /IT-skills-github-pages
theme: minima

header_pages:
  - index.md
  - about.md
  - contact.md

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/ACMGLLC

markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap




